### ISSUE TITLE
building HYPRE 2.12.0 with Visual Studio 2005: problem with empty macro PUSH_RANGE_PAYLOAD

### ISSUE THREAD

**Issue by janusw** [LLNL/hypre#17]
After fixing issues #12, #14 and #16, my branch

https://github.com/janusw/hypre/tree/v2.12.0-vs

still does not compile with VS 2005. The error I get is

```
..\parcsr_ls\ams.c(70) : error C2143: Syntaxfehler: Es fehlt ';' vor 'Typ'
```

It seems to be connected to the preprocessor macro PUSH_RANGE_PAYLOAD in the previous line, which is apparently empty/undefined in my setup. Thus the line
```
	 PUSH_RANGE_PAYLOAD("RELAX",4,sweep);
```
is evaluated to an almost empty line, containing just a semicolon, which for some reason seems to be a problem for VS05 (while VS15 and other compilers can cope with it just fine).

Cheers,
Janus

**Comment by janusw** [comment]
Simply removing the semicolon after the macro call could be a possible fix. However, I noticed that there are other instances of the macro call, where VS05 does not complain. The problem seems to be specific to the macro appearing before a variable-declaration line, which is certainly a compiler bug.

As a workaround I chose to just swap the two lines (which should be ok AFAICS), see the commit referenced above.

Cheers,
Janus

**Comment by rfalgout** [comment]
Hi Janus,

Wanted to let you know that the next release of hypre (this week) should work on VS2017, which is the only thing we can test on right now.  Some of the issues you mention in your previous issues have been addressed, but we have not yet looked through all of them.

How are you able to test so many different VS versions, BTW?  Thanks!

-Rob

**Comment by janusw** [comment]
Hi Rob,

thanks for the update. I just tried your release 2.12.1 with VS 2017, but unfortunately I still see the errors reported in #14 (or at least very similar ones). Note that I'm using `-DHYPRE_SEQUENTIAL=ON -DHYPRE_USING_OPENMP=ON` (not sure if that makes a difference). Also I'm seeing cmake warnings about policy CMP0054 (with cmake 3.9).

> How are you able to test so many different VS versions, BTW?

I essentially tried only two of them: I started with VS 2005, and after having so much trouble with HYPRE I decided to try VS 2015 on another machine. By now I have moved to VS 2017, so I don't care about the older versions any more (but other people might).

Cheers,
Janus

**Comment by rfalgout** [comment]
Hi Janus,

We haven't done the release yet.  It will be 2.13.0 and should come by tomorrow.  Thanks for all your help on this!

-Rob

**Comment by janusw** [comment]
It seems that #16 is also still biting. Have you actually tested VS17?

**Comment by rfalgout** [comment]
Closing, since this does not appear to be an issue on later versions of VS and hypre 2.13.0
